### ISSUE TITLE
Decide which projects to study

### ISSUE THREAD

**Issue by coco-lab-2022** [CocoLab-2022/TriangleinNetwork#1]
We need to first determine **which projects to study**. 

Previously, we usually have some difficulties to justify which project to use. So a safe strategy is:
Either do a random sampling (What Yisi Han did), or use the list of projects used by others (For instance, Yue's 54 projects) 

Anyway, we need to decide it. I suggest all of us think a little bit and discuss in tmr's meeting.

**Comment by yuanluzhan** [comment]
I vote to random sampling. 
We are investigating a totally new problem compared with Yue's research.
Moreover, random sampling selection strategy is more convincing.

**Comment by coco-lab-2022** [comment]
Seems sampling wins, so close this issue.
