### ISSUE TITLE
How to build network?

### ISSUE THREAD

**Issue by coco-lab-2022** [CocoLab-2022/TriangleinNetwork#2]
Multiple ways to built developer networks. I put some references in the "Resources" section.
We need to decide which to use by some time next month.

**Comment by coco-lab-2022** [comment]
Hi, there!

**Comment by 19991010wan** [comment]
Choose the approach of the second paper "Understanding a Developer Social Network and its Evolution" to build a network by mining github's bug reports for comments, but don't know how to get github's data yet

**Comment by coco-lab-2022** [comment]
I think this issue has been solved. @19991010wan commit the code I sent to you (and your changes) once you finish compiling the networks.
