### ISSUE TITLE
Random sampling

### ISSUE THREAD

**Issue by coco-lab-2022** [CocoLab-2022/TriangleinNetwork#3]
Get 200 out from the 2000 list

**Comment by yuanluzhan** [comment]
assigned to ？

**Comment by 19991010wan** [comment]
Wrote a random number program, have selected

**Comment by 19991010wan** [comment]
![4fee126cd4e5c77c5e1a9090c3af8e0](https://user-images.githubusercontent.com/66284746/166880789-7b3e7f81-486f-47e5-adc4-f200fc99e5d3.png)

**Comment by coco-lab-2022** [comment]
I would like to close it
